# SonarCloud configuration for EventPark Django
sonar.projectKey=gmaniram1509_Event_park
sonar.organization=gmaniram1509

sonar.projectName=EventPark
sonar.projectVersion=1.0

# Source — Django app only
sonar.sources=core
sonar.python.version=3.12

# Exclusions
sonar.exclusions=\
  **/migrations/**, \
  **/__pycache__/**, \
  **/staticfiles/**, \
  **/*.pyc, \
  **/db.sqlite3

sonar.sourceEncoding=UTF-8
